name: deploy doxygen to github pages

on:
  push:
    branches: [ docs ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen docs
      run: |
        mkdir -p docs/output
        doxygen docs/Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html/
        destination_dir: .
        keep_files: false
